### ISSUE TITLE
Python segfault crashes if a initialize() method throws an exception

### ISSUE THREAD

**Issue by simonw** [coleifer/sqlite-vtfunc#3]
Here's a full transcript (after installing using the steps in #2):

```
(vtfunc-demo) sqlite-vtfunc-master $ python
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re, requests, sqlite3
>>> from vtfunc import TableFunction
>>> 
>>> class Scraper(TableFunction):
...     params = ['url']  # Function argument names.
...     columns = ['href', 'description']  # Result rows have these columns.
...     name = 'scraper'  # Name we use to invoke the function from SQL.
...     def initialize(self, url):
...         # Note that this is bytes:
...         self.html = requests.get(url).content
...         self._iter = re.finditer(
...             '<a[^\>]+?href="([^\"]+?)"[^\>]*?>([^\<]+?)</a>',
...             self.html)
...     def iterate(self, idx):
...         return next(self._iter).groups()
... 
>>> conn = sqlite3.connect(':memory:')
>>> Scraper.register(conn)
>>> curs = conn.execute('SELECT * FROM scraper(?) ORDER BY length(description) DESC  LIMIT 3', ('https://news.ycombinator.com/',))
Traceback (most recent call last):
  File "<stdin>", line 10, in initialize
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 229, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: cannot use a string pattern on a bytes-like object
Exception ignored in: 'vtfunc.pwFilter'
Traceback (most recent call last):
  File "<stdin>", line 10, in initialize
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 229, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: cannot use a string pattern on a bytes-like object
Segmentation fault: 11
```

Here's that code in an easier-to-copy-and-paste format:

```
import re, requests, sqlite3
from vtfunc import TableFunction

class Scraper(TableFunction):
    params = ['url']  # Function argument names.
    columns = ['href', 'description']  # Result rows have these columns.
    name = 'scraper'  # Name we use to invoke the function from SQL.
    def initialize(self, url):
        # Note that this is bytes:
        self.html = requests.get(url).content
        self._iter = re.finditer(
            '<a[^\>]+?href="([^\"]+?)"[^\>]*?>([^\<]+?)</a>',
            self.html)
    def iterate(self, idx):
        return next(self._iter).groups()

conn = sqlite3.connect(':memory:')
Scraper.register(conn)
curs = conn.execute('SELECT * FROM scraper(?) ORDER BY length(description) DESC  LIMIT 3', ('https://news.ycombinator.com/',))
```

If I change that line to `self.html = requests.get(url).content.decode('utf8')` it works and I get the following:

```
>>> conn = sqlite3.connect(':memory:')
>>> Scraper.register(conn)
>>> curs = conn.execute('SELECT * FROM scraper(?) ORDER BY length(description) DESC  LIMIT 3', ('https://news.ycombinator.com/',))
>>> print(curs.fetchall())
[('https://www.ntsb.gov/investigations/AccidentReports/Reports/HWY18MH010-prelim.pdf', 'Uber Self-Driving Car That Struck Pedestrian Wasn’t Set to Stop in an Emergency'), ('https://www.macrumors.com/2018/05/24/apple-knew-about-bendgate-and-touch-disease/', 'Apple Knew About iPhone 6 Bendgate/Touch Disease Months Before Repair Programs'), ('https://www.theguardian.com/technology/2018/may/24/mark-zuckerberg-set-up-fraudulent-scheme-weaponise-data-facebook-court-case-alleges?CMP=share_btn_tw', "Zuckerberg set up fraudulent scheme to 'weaponise' data, court case alleges")]
```

**Comment by simonw** [comment]
It looks like this is the code which is supposed to catch these kinds of exceptions:

https://github.com/coleifer/sqlite-vtfunc/blob/23ddc21789a9e0578bd9fef8c558e39de9dd33bc/vtfunc.pyx#L264-L269

I'm not sure why `return SQLITE_ERROR` there is causing a segfault. Maybe that catch block should set `pCur.stopped = True` as well?

**Comment by simonw** [comment]
Oh hang on... the clue is in the traceback: `Exception ignored in: 'vtfunc.pwFilter'`

Makes sense. The exception is being triggered in the `initialize()' method. And it looks like there's no try/except around the call to that from the `pwFilter` function:

https://github.com/coleifer/sqlite-vtfunc/blob/23ddc21789a9e0578bd9fef8c558e39de9dd33bc/vtfunc.pyx#L371-L372

**Comment by coleifer** [comment]
Thanks for reporting, fixed.

**Comment by simonw** [comment]
I just tested this against the new 0.3.3 release from PyPI and it worked! Thanks for the fix.

```
>>> curs = conn.execute('SELECT * FROM scraper(?) ORDER BY length(description) DESC  LIMIT 3', ('https://news.ycombinator.com/',))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: SQL logic error
```
